"""
ï»¿CPU Usage Collector
Auto-generated by BIFF Collector Builder

Uses psutil for system metrics
"""

import sys

try:
    import psutil
except ImportError:
    print("Error: psutil not installed. Run: pip install psutil", file=sys.stderr)
    sys.exit(1)

def collect_ï»¿cpu_usage():
    """Collect ï»¿CPU Usage using psutil"""
    try:
        # CPU usage percentage
        cpu_percent = psutil.cpu_percent(interval=1)
        return str(cpu_percent)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    value = collect_ï»¿cpu_usage()
    if value is not None:
        print(value)
    else:
        sys.exit(1)
