"""
Dashboard Composer

Generates complete Marvin application configurations from templates.
Creates App.Config.xml and associated tab files with intelligent widget placement.
"""

from pathlib import Path
from typing import List, Dict, Optional
from abc import ABC, abstractmethod

from ..utils.minion_discovery import MinionDataSourceDiscovery, DataSource


class DashboardComposer(ABC):
    """Base class for dashboard composers"""
    
    def __init__(self, minion_config_path: Optional[Path] = None):
        """
        Initialize dashboard composer.
        
        Args:
            minion_config_path: Path to MinionConfig.xml for data discovery
        """
        self.config_path = Path(minion_config_path) if minion_config_path else None
        self.discovery = None
        self.data_sources: List[DataSource] = []
        
        if self.config_path and self.config_path.exists():
            self.discovery = MinionDataSourceDiscovery(str(self.config_path))
            self.data_sources = self.discovery.discover()
    
    @abstractmethod
    def generate_dashboard(self, output_dir: Path) -> Dict[str, str]:
        """
        Generate dashboard configuration files.
        
        Args:
            output_dir: Directory to write configuration files
            
        Returns:
            Dictionary mapping filename to content
        """
        pass
    
    def _generate_app_config(self, title: str, tabs: List[Dict]) -> str:
        """
        Generate main App.Config.xml file.
        
        Args:
            title: Application title
            tabs: List of tab definitions
            
        Returns:
            XML string for App.Config.xml
        """
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!--',
            f'  {title}',
            '  Generated by BIFF Agents - Marvin GUI Composer',
            '-->',
            '<Application>',
            f'    <Title>{title}</Title>',
            '    <Width>1600</Width>',
            '    <Height>900</Height>',
            '    <Fullscreen>false</Fullscreen>',
            '',
            '    <!-- Oscar Connection -->',
            '    <OscarConnection IP="localhost" Port="5100"/>',
            '',
            '    <!-- Tabs -->',
        ]
        
        for tab in tabs:
            xml_lines.append(f'    <Tab File="{tab["file"]}">')
            xml_lines.append(f'        <Name>{tab["name"]}</Name>')
            xml_lines.append('    </Tab>')
        
        xml_lines.extend([
            '</Application>',
            ''
        ])
        
        return '\n'.join(xml_lines)
    
    def _generate_tab(self, tab_name: str, widgets: List[str], columns: int = 4) -> str:
        """
        Generate tab XML with widgets.
        
        Args:
            tab_name: Tab display name
            widgets: List of widget XML strings
            columns: Number of columns in grid
            
        Returns:
            XML string for tab file
        """
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!--',
            f'  Tab: {tab_name}',
            '  Generated by BIFF Agents - Marvin GUI Composer',
            '-->',
            '<Tab>',
            f'    <TabName>{tab_name}</TabName>',
            '',
            f'    <Grid columns="{columns}">',
            ''
        ]
        
        # Add widgets
        for widget in widgets:
            # Indent widget XML
            widget_lines = widget.split('\n')
            for line in widget_lines:
                if line.strip():  # Skip empty lines
                    xml_lines.append('        ' + line)
            xml_lines.append('')
        
        xml_lines.extend([
            '    </Grid>',
            '</Tab>',
            ''
        ])
        
        return '\n'.join(xml_lines)
    
    def _create_text_widget(self, title: str, source: DataSource, 
                           row: int, col: int, units: str = "") -> str:
        """Generate text widget XML"""
        xml = f'<Widget File="Text/Text.xml" row="{row}" column="{col}" Align="C">\n'
        xml += f'    <Title>{title}</Title>\n'
        xml += f'    <MinionSrc Namespace="{source.namespace}" ID="{source.collector_id}"/>\n'
        if units:
            xml += f'    <Suffix> {units}</Suffix>\n'
        xml += '</Widget>'
        return xml
    
    def _create_led_widget(self, title: str, source: DataSource,
                          row: int, col: int, condition: str = ">50") -> str:
        """Generate LED widget XML"""
        xml = f'<Widget File="LED/LED.xml" row="{row}" column="{col}">\n'
        xml += f'    <Title>{title}</Title>\n'
        xml += f'    <MinionSrc Namespace="{source.namespace}" ID="{source.collector_id}"/>\n'
        xml += f'    <OnCondition>{condition}</OnCondition>\n'
        xml += '    <Color>Green</Color>\n'
        xml += '    <Height>24</Height>\n'
        xml += '    <Width>24</Width>\n'
        xml += '</Widget>'
        return xml
    
    def _create_gauge_widget(self, title: str, source: DataSource,
                            row: int, col: int, 
                            min_val: float = 0, max_val: float = 100,
                            units: str = "", row_span: int = 2, col_span: int = 2) -> str:
        """Generate gauge widget XML"""
        xml = f'<Widget File="Gauge/Radial1Horizontal.xml" row="{row}" column="{col}"'
        if row_span > 1:
            xml += f' rowSpan="{row_span}"'
        if col_span > 1:
            xml += f' columnSpan="{col_span}"'
        xml += '>\n'
        xml += f'    <Title>{title}</Title>\n'
        xml += f'    <MinionSrc Namespace="{source.namespace}" ID="{source.collector_id}"/>\n'
        xml += f'    <MinValue>{int(min_val)}</MinValue>\n'
        xml += f'    <MaxValue>{int(max_val)}</MaxValue>\n'
        if units:
            xml += f'    <UnitsOverride>{units}</UnitsOverride>\n'
        xml += '    <MajorTicks>10</MajorTicks>\n'
        
        # Add standard 3-zone coloring
        xml += '    <Zones>\n'
        range_span = max_val - min_val
        zone1_end = min_val + (range_span * 0.7)
        zone2_end = min_val + (range_span * 0.9)
        
        xml += '        <Zone>\n'
        xml += f'            <Start>{min_val}</Start>\n'
        xml += f'            <End>{zone1_end}</End>\n'
        xml += '            <Color>rgb(0, 255, 0)</Color>\n'
        xml += '        </Zone>\n'
        xml += '        <Zone>\n'
        xml += f'            <Start>{zone1_end}</Start>\n'
        xml += f'            <End>{zone2_end}</End>\n'
        xml += '            <Color>rgb(255, 255, 0)</Color>\n'
        xml += '        </Zone>\n'
        xml += '        <Zone>\n'
        xml += f'            <Start>{zone2_end}</Start>\n'
        xml += f'            <End>{max_val}</End>\n'
        xml += '            <Color>rgb(255, 0, 0)</Color>\n'
        xml += '        </Zone>\n'
        xml += '    </Zones>\n'
        xml += '</Widget>'
        return xml
    
    def _create_chart_widget(self, title: str, sources: List[DataSource],
                            row: int, col: int,
                            row_span: int = 2, col_span: int = 4,
                            history: int = 60) -> str:
        """Generate chart widget XML"""
        xml = f'<Widget File="Chart/LineChart.xml" row="{row}" column="{col}"'
        if row_span > 1:
            xml += f' rowSpan="{row_span}"'
        if col_span > 1:
            xml += f' columnSpan="{col_span}"'
        xml += '>\n'
        xml += f'    <Title>{title}</Title>\n'
        xml += '    <xAxisLabel>Time</xAxisLabel>\n'
        xml += f'    <HistorySize>{history}</HistorySize>\n'
        xml += '    <yAxisLabel>Value</yAxisLabel>\n'
        xml += '    <ShowLegend>true</ShowLegend>\n'
        xml += '    <Series>\n'
        
        colors = ['#0000FF', '#00FF00', '#FF0000', '#FF8800', '#8800FF', '#00FFFF']
        for i, source in enumerate(sources[:6]):  # Max 6 series for visibility
            color = colors[i % len(colors)]
            label = source.collector_id.replace('.', ' ').title()
            
            xml += '        <SeriesSet>\n'
            xml += f'            <Title>{label}</Title>\n'
            xml += f'            <MinionSrc Namespace="{source.namespace}" ID="{source.collector_id}"/>\n'
            xml += f'            <Color>{color}</Color>\n'
            xml += '        </SeriesSet>\n'
        
        xml += '    </Series>\n'
        xml += '</Widget>'
        return xml
    
    def save_dashboard(self, output_dir: Path) -> List[Path]:
        """
        Generate and save dashboard to directory.
        
        Args:
            output_dir: Output directory
            
        Returns:
            List of generated file paths
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        
        files = self.generate_dashboard(output_dir)
        saved_paths = []
        
        for filename, content in files.items():
            filepath = output_dir / filename
            filepath.write_text(content, encoding='utf-8')
            saved_paths.append(filepath)
            print(f"✅ Generated: {filepath.name}")
        
        return saved_paths
