"""
Minion Collector Builder

Interactive wizard for creating new Minion collectors with templates and configuration updates.
"""

import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


class CollectorTemplate:
    """Base class for collector templates"""
    
    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
    
    def generate(self, params: Dict) -> str:
        """Generate collector code from parameters"""
        raise NotImplementedError("Subclasses must implement generate()")
    
    def get_required_params(self) -> List[str]:
        """Get list of required parameters for this template"""
        raise NotImplementedError("Subclasses must implement get_required_params()")


class ShellCommandTemplate(CollectorTemplate):
    """Template for wrapping shell commands"""
    
    def __init__(self):
        super().__init__(
            "Shell Command",
            "Wrap an existing command-line tool (e.g., nvidia-smi, sensors, iperf)"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'command', 'parse_method']
    
    def generate(self, params: Dict) -> str:
        """Generate shell command wrapper collector"""
        metric_name = params['metric_name']
        command = params['command']
        parse_method = params.get('parse_method', 'line')  # line, json, csv, regex
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

Wraps command: {command}
"""

import subprocess
import sys

def collect_{metric_name.lower().replace(' ', '_').replace('-', '_')}():
    """Collect {metric_name} metric"""
    try:
        result = subprocess.run(
            {repr(command.split())},
            capture_output=True,
            text=True,
            timeout=5
        )
        
        if result.returncode != 0:
            print(f"Error: {{result.stderr}}", file=sys.stderr)
            return None
        
        # Parse output
        output = result.stdout.strip()
'''
        
        if parse_method == 'line':
            code += '''        
        # Return first line
        return output.split('\\n')[0] if output else None
'''
        elif parse_method == 'json':
            code += '''
        import json
        try:
            data = json.loads(output)
            # TODO: Extract specific value from JSON
            return str(data)
        except json.JSONDecodeError:
            return None
'''
        elif parse_method == 'regex':
            code += '''
        import re
        # TODO: Add regex pattern to extract value
        pattern = r'(\\d+\\.?\\d*)'
        match = re.search(pattern, output)
        return match.group(1) if match else None
'''
        else:  # csv or other
            code += '''
        # Return raw output
        return output
'''
        
        code += '''
    except subprocess.TimeoutExpired:
        print("Error: Command timed out", file=sys.stderr)
        return None
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    value = collect_'''
        code += metric_name.lower().replace(' ', '_').replace('-', '_')
        code += '''()
    if value is not None:
        print(value)
    else:
        sys.exit(1)
'''
        
        return code


class FileParserTemplate(CollectorTemplate):
    """Template for parsing files"""
    
    def __init__(self):
        super().__init__(
            "File Parser",
            "Read metrics from log files, data files, or system files"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'file_path', 'parse_method']
    
    def generate(self, params: Dict) -> str:
        """Generate file parser collector"""
        metric_name = params['metric_name']
        file_path = params['file_path']
        parse_method = params.get('parse_method', 'line')
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

Reads from: {file_path}
"""

import sys
from pathlib import Path

def collect_{metric_name.lower().replace(' ', '_').replace('-', '_')}():
    """Collect {metric_name} from file"""
    try:
        file_path = Path({repr(file_path)})
        if not file_path.exists():
            print(f"Error: File not found: {{file_path}}", file=sys.stderr)
            return None
        
        with open(file_path, 'r') as f:
            content = f.read()
        
'''
        
        if parse_method == 'line':
            code += '''        # Return first line
        lines = content.strip().split('\\n')
        return lines[0] if lines else None
'''
        elif parse_method == 'last_line':
            code += '''        # Return last line
        lines = content.strip().split('\\n')
        return lines[-1] if lines else None
'''
        elif parse_method == 'json':
            code += '''        import json
        try:
            data = json.loads(content)
            # TODO: Extract specific value from JSON
            return str(data)
        except json.JSONDecodeError:
            return None
'''
        elif parse_method == 'regex':
            code += '''        import re
        # TODO: Add regex pattern to extract value
        pattern = r'(\\d+\\.?\\d*)'
        match = re.search(pattern, content)
        return match.group(1) if match else None
'''
        
        code += '''
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    value = collect_'''
        code += metric_name.lower().replace(' ', '_').replace('-', '_')
        code += '''()
    if value is not None:
        print(value)
    else:
        sys.exit(1)
'''
        
        return code


class PsutilTemplate(CollectorTemplate):
    """Template for psutil-based system metrics"""
    
    def __init__(self):
        super().__init__(
            "System Metrics (psutil)",
            "Collect system metrics using Python psutil library"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'metric_type']
    
    def generate(self, params: Dict) -> str:
        """Generate psutil collector"""
        metric_name = params['metric_name']
        metric_type = params.get('metric_type', 'cpu')  # cpu, memory, disk, network
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

Uses psutil for system metrics
"""

import sys

try:
    import psutil
except ImportError:
    print("Error: psutil not installed. Run: pip install psutil", file=sys.stderr)
    sys.exit(1)

def collect_{metric_name.lower().replace(' ', '_').replace('-', '_')}():
    """Collect {metric_name} using psutil"""
    try:
'''
        
        if metric_type == 'cpu':
            code += '''        # CPU usage percentage
        cpu_percent = psutil.cpu_percent(interval=1)
        return str(cpu_percent)
'''
        elif metric_type == 'memory':
            code += '''        # Memory usage
        mem = psutil.virtual_memory()
        return str(mem.percent)  # or mem.used, mem.available, etc.
'''
        elif metric_type == 'disk':
            code += '''        # Disk usage
        disk = psutil.disk_usage('/')
        return str(disk.percent)  # or disk.used, disk.free, etc.
'''
        elif metric_type == 'network':
            code += '''        # Network I/O
        net_io = psutil.net_io_counters()
        return str(net_io.bytes_sent)  # or bytes_recv, packets_sent, etc.
'''
        
        code += '''
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    value = collect_'''
        code += metric_name.lower().replace(' ', '_').replace('-', '_')
        code += '''()
    if value is not None:
        print(value)
    else:
        sys.exit(1)
'''
        
        return code


class APIPollerTemplate(CollectorTemplate):
    """Template for API polling"""
    
    def __init__(self):
        super().__init__(
            "API Poller",
            "Poll REST APIs and extract JSON values"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'api_url']
    
    def generate(self, params: Dict) -> str:
        """Generate API poller collector"""
        metric_name = params['metric_name']
        api_url = params['api_url']
        json_path = params.get('json_path', '')
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

API endpoint: {api_url}
"""

import sys

try:
    import requests
except ImportError:
    print("Error: requests not installed. Run: pip install requests", file=sys.stderr)
    sys.exit(1)

def collect_{metric_name.lower().replace(' ', '_').replace('-', '_')}():
    """Poll API for {metric_name}"""
    try:
        response = requests.get(
            {repr(api_url)},
            timeout=5
        )
        response.raise_for_status()
        
        data = response.json()
'''
        
        if json_path:
            code += f'''        
        # Extract value from JSON path: {json_path}
        # TODO: Implement path navigation
        value = data.get({repr(json_path)})
'''
        else:
            code += '''        
        # TODO: Navigate to specific value in JSON response
        value = data
'''
        
        code += '''        
        return str(value) if value is not None else None
        
    except requests.RequestException as e:
        print(f"API Error: {e}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    value = collect_'''
        code += metric_name.lower().replace(' ', '_').replace('-', '_')
        code += '''()
    if value is not None:
        print(value)
    else:
        sys.exit(1)
'''
        
        return code


class PluginTemplate(CollectorTemplate):
    """Template for Python plugin collectors"""
    
    def __init__(self):
        super().__init__(
            "Python Plugin",
            "Python module with entry point function"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'function_name']
    
    def generate(self, params: Dict) -> str:
        """Generate plugin template"""
        metric_name = params['metric_name']
        function_name = params.get('function_name', 'collect')
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

Python plugin with entry point function
"""

import sys

def {function_name}():
    """
    Main entry point for {metric_name} collection
    
    Returns:
        str: Metric value as string
    """
    # TODO: Implement your metric collection logic here
    
    # Example:
    # 1. Read from sensor/API/file
    # 2. Process/calculate value
    # 3. Return as string
    
    return "0"  # Replace with actual value

if __name__ == '__main__':
    try:
        value = {function_name}()
        if value is not None:
            print(value)
        else:
            print("Error: No value returned", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        print(f"Error: {{e}}", file=sys.stderr)
        sys.exit(1)
'''
        
        return code


class PluginFrameworkTemplate(CollectorTemplate):
    """Template for Plugin with Framework Interface (dynamic collector registration)"""
    
    def __init__(self):
        super().__init__(
            "Plugin Framework Interface",
            "Plugin with frameworkInterface parameter for dynamic collector registration"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_name', 'function_name', 'discovery_mode']
    
    def generate(self, params: Dict) -> str:
        """Generate plugin with framework interface"""
        metric_name = params['metric_name']
        function_name = params.get('function_name', 'collect')
        discovery_mode = params.get('discovery_mode', 'dynamic')  # 'dynamic' or 'static'
        static_ids = params.get('static_ids', [])
        
        # Generate collector ID list for static mode
        collector_ids_code = ""
        if discovery_mode == 'static' and static_ids:
            ids_list = ', '.join([f'"{id}"' for id in static_ids])
            collector_ids_code = f"\n# Static collector IDs\nCOLLECTOR_IDS = [{ids_list}]\n"
        
        code = f'''"""
{metric_name} Collector
Auto-generated by BIFF Collector Builder

Plugin with Framework Interface for dynamic collector registration
Discovery Mode: {discovery_mode}
"""

import sys
{collector_ids_code}
def {function_name}(frameworkInterface):
    """
    Main entry point for {metric_name} collection with framework interface
    
    Args:
        frameworkInterface: Minion framework interface providing:
            - Logger: Logger instance for logging
            - AddCollector(id): Register new collector dynamically
            - DoesCollectorExist(id): Check if collector already exists
            - SetCollectorValue(id, value): Update collector value
    
    Returns:
        str: "HelenKeller" to suppress standard output (framework handles data)
    """
    # Get logger from framework
    Logger = frameworkInterface.Logger
    
    try:
        Logger.info("Starting {metric_name} collector")
        
'''
        
        if discovery_mode == 'dynamic':
            code += '''        # Dynamic discovery example
        # Discover collectors at runtime (e.g., Docker containers, network devices)
        
        # TODO: Implement your discovery logic
        # Example: discovered_items = get_active_items()
        discovered_items = []  # Replace with actual discovery
        
        # Register and update collectors dynamically
        for item in discovered_items:
            collector_id = f"item.{item['name']}.{item['metric']}"
            
            # Register collector if it doesn't exist
            if not frameworkInterface.DoesCollectorExist(collector_id):
                frameworkInterface.AddCollector(collector_id)
                Logger.info(f"Registered new collector: {collector_id}")
            
            # Update collector value
            frameworkInterface.SetCollectorValue(collector_id, item['value'])
        
        Logger.info(f"Updated {len(discovered_items)} collectors")
'''
        else:  # static mode
            code += '''        # Static collector IDs (defined at config time)
        
        for collector_id in COLLECTOR_IDS:
            # TODO: Implement collection logic for each ID
            value = "0"  # Replace with actual collection
            
            # Register collector if it doesn't exist
            if not frameworkInterface.DoesCollectorExist(collector_id):
                frameworkInterface.AddCollector(collector_id)
                Logger.info(f"Registered collector: {collector_id}")
            
            # Update collector value
            frameworkInterface.SetCollectorValue(collector_id, value)
        
        Logger.info(f"Updated {len(COLLECTOR_IDS)} collectors")
'''
        
        code += f'''        
    except Exception as Ex:
        Logger.error(f"Error in {metric_name} collector: {{Ex}}")
    
    # Return "HelenKeller" to suppress standard output
    # Framework interface handles all data transmission
    return "HelenKeller"


if __name__ == '__main__':
    # Test mode - create mock framework interface
    class MockFramework:
        class MockLogger:
            def info(self, msg): print(f"INFO: {{msg}}")
            def error(self, msg): print(f"ERROR: {{msg}}", file=sys.stderr)
        
        def __init__(self):
            self.Logger = self.MockLogger()
            self.collectors = {{}}
        
        def AddCollector(self, id):
            self.collectors[id] = None
            print(f"Added collector: {{id}}")
        
        def DoesCollectorExist(self, id):
            return id in self.collectors
        
        def SetCollectorValue(self, id, value):
            self.collectors[id] = value
            print(f"Set {{id}} = {{value}}")
    
    # Run with mock framework
    mock = MockFramework()
    result = {function_name}(mock)
    print(f"\\nReturn value: {{result}}")
    print(f"Registered collectors: {{list(mock.collectors.keys())}}")
'''
        
        return code
    
    def get_usage_notes(self) -> str:
        """Return usage notes for this template"""
        return """
Plugin Framework Interface Notes:
-----------------------------------
This template generates collectors that use the Minion framework interface
for DYNAMIC collector registration - collectors are discovered and registered
at runtime rather than defined in XML.

Key Features:
  • Logger integration from framework
  • Dynamic collector registration with AddCollector()
  • Check existence with DoesCollectorExist()
  • Update values with SetCollectorValue()
  • Returns "HelenKeller" to suppress standard output

Production Examples (Intel Vision Demo):
  • Docker_Stats.py: Discovers running containers dynamically
  • LinuxNetwork.py: Discovers network queues (tx_queue_0, tx_queue_1, ...)
  • 12 collectors use this pattern (40% adoption rate)

Why Use Framework Interface:
  ✓ Unknown number of collectors at config time
  ✓ Collectors appear/disappear dynamically (Docker containers)
  ✓ Auto-discovery patterns (enumerate devices, parse lists)
  ✓ Cleaner than subprocess output parsing
  ✓ Direct control over collector lifecycle

XML Configuration:
  <Plugin>
    <PythonFile>Collectors/YourCollector.py</PythonFile>
    <EntryPoint>your_function_name</EntryPoint>
    <Param>optional_param=value</Param>
  </Plugin>
"""


class DynamicCollectorTemplate(CollectorTemplate):
    """Template for DynamicCollector file watcher (XML-only, no Python code)"""
    
    def __init__(self):
        super().__init__(
            "DynamicCollector File Watcher",
            "Watch a file for metrics in 'name=value' format (zero instrumentation)"
        )
    
    def get_required_params(self) -> List[str]:
        return ['metric_prefix', 'file_path', 'frequency', 'precision']
    
    def generate(self, params: Dict) -> str:
        """Generate DynamicCollector XML configuration"""
        metric_prefix = params['metric_prefix']
        file_path = params['file_path']
        frequency = params.get('frequency', 1000)
        precision = params.get('precision', 0)
        send_on_change = params.get('send_on_change', False)
        
        # Build XML line by line
        lines = []
        if send_on_change:
            lines.append(f'<DynamicCollector Prefix="{metric_prefix}." OnlySendOnChange="True" Frequency="{frequency}">')
        else:
            lines.append(f'<DynamicCollector Prefix="{metric_prefix}." Frequency="{frequency}">')
        
        lines.append(f'    <File>{file_path}</File>')
        lines.append(f'    <Precision>{precision}</Precision>')
        lines.append('</DynamicCollector>')
        
        return '\n'.join(lines)
    
    def get_usage_notes(self) -> str:
        """Return usage notes for this collector type"""
        return """
DynamicCollector File Watcher - Usage Notes:
--------------------------------------------
• File format: Each line should be 'metric.name=value'
• Example file content:
    cpu.usage=45.2
    memory.free=8192
    disk.io=1234
    
• Prefix is automatically added to all metric names
• All metrics in file are auto-discovered
• No Python code required - pure XML configuration
• Perfect for test harnesses, CI/CD outputs, application logs

Production Example (Intel Vision Demo):
  15 instances collecting test results from files
  Zero code maintenance, pure data-driven monitoring
"""


class CollectorWizard:
    """Interactive wizard for creating new collectors"""
    
    TEMPLATES = {
        'shell': ShellCommandTemplate(),
        'file': FileParserTemplate(),
        'psutil': PsutilTemplate(),
        'api': APIPollerTemplate(),
        'plugin': PluginTemplate(),
        'plugin_framework': PluginFrameworkTemplate(),
        'dynamic_file': DynamicCollectorTemplate()
    }
    
    DATA_SOURCE_TYPES = {
        'system': 'System metrics (CPU, memory, disk, network)',
        'command': 'Wrap existing command-line tool',
        'file': 'Parse file or log file',
        'dynamic_file': 'File watcher (auto-discover metrics)',
        'api': 'Poll REST API',
        'plugin_framework': 'Plugin with framework interface (dynamic discovery)',
        'custom': 'Custom Python code'
    }
    
    FREQUENCIES = {
        '500ms': 500,
        '1s': 1000,
        '5s': 5000,
        '10s': 10000,
        '30s': 30000,
        '60s': 60000
    }
    
    def __init__(self):
        self.responses = {}
    
    def _prompt(self, question: str, options: Optional[List[str]] = None, default: Optional[str] = None) -> str:
        """Prompt user for input (strips BOM for Windows PowerShell compatibility)"""
        if options:
            print(f"\n{question}")
            for i, option in enumerate(options, 1):
                print(f"  {i}. {option}")
            
            while True:
                choice = input(f"Choose (1-{len(options)}){f' [{default}]' if default else ''}: ").strip()
                
                # Strip BOM if present (Windows PowerShell compatibility)
                if choice.startswith('\ufeff'):
                    choice = choice[1:]
                elif choice.startswith('ï»¿'):
                    choice = choice[3:]
                
                if not choice and default:
                    return default
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(options):
                        return options[idx]
                except ValueError:
                    pass
                print("Invalid choice. Try again.")
        else:
            prompt_text = f"{question}"
            if default:
                prompt_text += f" [{default}]"
            prompt_text += ": "
            
            response = input(prompt_text).strip()
            
            # Strip BOM if present (Windows PowerShell/echo adds UTF-8 BOM)
            if response.startswith('\ufeff'):
                response = response[1:]
            elif response.startswith('ï»¿'):
                response = response[3:]
            
            return response if response else (default or "")
    
    def _validate_metric_id(self, metric_id: str) -> Tuple[bool, str]:
        """Validate metric ID format"""
        if not metric_id:
            return False, "Metric ID cannot be empty"
        
        # Check for valid characters (alphanumeric, dots, underscores, hyphens)
        import re
        if not re.match(r'^[a-zA-Z0-9._-]+$', metric_id):
            return False, "Metric ID can only contain letters, numbers, dots, underscores, and hyphens"
        
        # Check if it starts with a letter
        if not metric_id[0].isalpha():
            return False, "Metric ID must start with a letter"
        
        return True, ""
    
    def run_wizard(self) -> Dict:
        """Run interactive wizard"""
        print("\n" + "="*70)
        print("  BIFF Collector Builder - Interactive Wizard")
        print("="*70)
        
        # Step 1: Metric name
        print("\n📊 Step 1: What metric do you want to collect?")
        metric_name = self._prompt("Metric name (e.g., GPU Temperature, API Response Time)")
        self.responses['metric_name'] = metric_name
        
        # Step 2: Data source type
        print("\n📁 Step 2: What type of data source?")
        source_options = list(self.DATA_SOURCE_TYPES.keys())
        source_descriptions = [f"{k}: {v}" for k, v in self.DATA_SOURCE_TYPES.items()]
        source_choice = self._prompt("Data source type", source_descriptions)
        source_type = source_choice.split(':')[0]
        self.responses['source_type'] = source_type
        
        # Step 3: Template selection
        if source_type == 'system':
            template_key = 'psutil'
            system_metric = self._prompt(
                "Which system metric?",
                ['CPU usage', 'Memory usage', 'Disk usage', 'Network I/O']
            )
            metric_type_map = {
                'CPU usage': 'cpu',
                'Memory usage': 'memory',
                'Disk usage': 'disk',
                'Network I/O': 'network'
            }
            self.responses['metric_type'] = metric_type_map.get(system_metric, 'cpu')
        elif source_type == 'command':
            template_key = 'shell'
            command = self._prompt("Command to run (e.g., nvidia-smi --query-gpu=temperature.gpu)")
            self.responses['command'] = command
            parse_method = self._prompt(
                "How to parse output?",
                ['First line', 'JSON', 'Regular expression', 'Raw output']
            )
            parse_map = {
                'First line': 'line',
                'JSON': 'json',
                'Regular expression': 'regex',
                'Raw output': 'raw'
            }
            self.responses['parse_method'] = parse_map.get(parse_method, 'line')
        elif source_type == 'file':
            template_key = 'file'
            file_path = self._prompt("File path to read (e.g., /var/log/app.log)")
            self.responses['file_path'] = file_path
            parse_method = self._prompt(
                "How to parse file?",
                ['First line', 'Last line', 'JSON', 'Regular expression']
            )
            parse_map = {
                'First line': 'line',
                'Last line': 'last_line',
                'JSON': 'json',
                'Regular expression': 'regex'
            }
            self.responses['parse_method'] = parse_map.get(parse_method, 'line')
        elif source_type == 'dynamic_file':
            template_key = 'dynamic_file'
            print("\n📝 DynamicCollector watches files with 'name=value' format")
            print("   Example file content:")
            print("     cpu.usage=45.2")
            print("     memory.free=8192")
            print("     disk.io=1234")
            file_path = self._prompt("File path to watch (e.g., testdata/metrics.txt)")
            self.responses['file_path'] = file_path
            
            # For DynamicCollector, we need a prefix instead of a single metric ID
            print("\n🏷️  Metric prefix (will be added to all discovered metrics)")
            suggested_prefix = metric_name.lower().replace(' ', '.').replace('_', '.')
            suggested_prefix = ''.join(c for c in suggested_prefix if c.isalnum() or c == '.')
            metric_prefix = self._prompt("Metric prefix", default=suggested_prefix)
            self.responses['metric_prefix'] = metric_prefix
            
            precision = self._prompt("Decimal precision (0 for integers)", default="0")
            self.responses['precision'] = int(precision)
            
            send_on_change = self._prompt(
                "Only send when values change?",
                ['No (send always)', 'Yes (send on change only)']
            )
            self.responses['send_on_change'] = send_on_change.startswith('Yes')
        elif source_type == 'api':
            template_key = 'api'
            api_url = self._prompt("API URL (e.g., http://localhost:8080/metrics)")
            self.responses['api_url'] = api_url
            json_path = self._prompt("JSON path to extract (optional, e.g., data.temperature)", default="")
            if json_path:
                self.responses['json_path'] = json_path
        elif source_type == 'plugin_framework':
            template_key = 'plugin_framework'
            print("\n🔌 Plugin Framework Interface allows dynamic collector registration")
            print("   Use this when:")
            print("     • Number of collectors is unknown at config time")
            print("     • Collectors appear/disappear dynamically (e.g., Docker containers)")
            print("     • Need to discover items at runtime (e.g., network devices)")
            
            function_name = self._prompt("Entry point function name", default="collect")
            self.responses['function_name'] = function_name
            
            discovery_mode = self._prompt(
                "Discovery mode",
                ['Dynamic (discover collectors at runtime)', 'Static (predefined collector IDs)']
            )
            
            if discovery_mode.startswith('Dynamic'):
                self.responses['discovery_mode'] = 'dynamic'
                print("\n   Dynamic mode examples:")
                print("     • Docker containers: enumerate running containers")
                print("     • Network queues: discover tx_queue_0, tx_queue_1, ...")
                print("     • You'll implement discovery logic in generated code")
            else:
                self.responses['discovery_mode'] = 'static'
                print("\n   Static mode: Enter collector IDs (comma-separated)")
                ids_input = self._prompt("Collector IDs (e.g., metric1,metric2,metric3)")
                static_ids = [id.strip() for id in ids_input.split(',') if id.strip()]
                self.responses['static_ids'] = static_ids
                print(f"   Will create {len(static_ids)} collectors: {', '.join(static_ids[:3])}{'...' if len(static_ids) > 3 else ''}")
        else:  # custom
            template_key = 'plugin'
            function_name = self._prompt("Entry point function name", default="collect")
            self.responses['function_name'] = function_name
        
        self.responses['template_key'] = template_key
        
        # Step 4: Collection frequency
        print("\n⏱️  Step 3: How often to collect?")
        freq_choice = self._prompt(
            "Collection frequency",
            list(self.FREQUENCIES.keys()),
            default='1s'
        )
        self.responses['frequency'] = self.FREQUENCIES[freq_choice]
        self.responses['frequency_display'] = freq_choice
        
        # Step 5: Metric ID (skip for dynamic_file and plugin_framework which register dynamically)
        if source_type not in ['dynamic_file', 'plugin_framework']:
            print("\n🔖 Step 4: Metric identifier")
            suggested_id = metric_name.lower().replace(' ', '.').replace('_', '.')
            suggested_id = ''.join(c for c in suggested_id if c.isalnum() or c == '.')
            
            while True:
                metric_id = self._prompt(f"Metric ID", default=suggested_id)
                valid, error = self._validate_metric_id(metric_id)
                if valid:
                    self.responses['metric_id'] = metric_id
                    break
                else:
                    print(f"❌ {error}")
        
        return self.responses
    
    def generate_collector(self, responses: Dict) -> str:
        """Generate collector code from wizard responses"""
        template_key = responses['template_key']
        template = self.TEMPLATES[template_key]
        
        return template.generate(responses)
    
    def save_collector(self, code: str, output_path: Path) -> None:
        """Save generated collector to file"""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(code)
