"""
LED Widget Builder

Creates LED indicator widgets for status displays.
Supports on/off states, colors, and data binding to Boolean or numeric sources.
"""

from pathlib import Path
from typing import Optional, Dict

from .widget_builder import WidgetBuilder
from ..utils.minion_discovery import DataSource


class LEDWidgetBuilder(WidgetBuilder):
    """Builder for LED indicator widgets"""
    
    WIDGET_FILE = "LED/LED.xml"
    
    COLORS = [
        "Green",
        "Red",
        "Yellow",
        "Blue",
        "Orange",
        "Purple",
        "White"
    ]
    
    def build_widget(self) -> str:
        """
        Interactive wizard to create LED widget.
        
        Returns:
            Widget XML string
        """
        config = {}
        
        # Step 1: Title/Label
        config['title'] = self._prompt("LED label/title", "Status")
        
        # Step 2: Data source selection
        print("\n📊 Step 2: Data Source")
        print("Select a data source for LED state (0=off, 1=on), or skip for manual control.")
        
        source = self.select_data_source()
        config['source'] = source
        
        # Step 3: On/Off threshold (if numeric source)
        if source:
            print("\n🎯 Step 3: Trigger Condition")
            print("LED turns ON when value meets this condition:")
            
            condition_type = self._prompt_choice(
                "Condition type",
                ["Equals (value == X)", "Greater than (value > X)", "Less than (value < X)"],
                default=1
            )
            
            config['condition_type'] = ['==', '>', '<'][condition_type]
            config['condition_value'] = self._prompt("Threshold value", "1")
        else:
            # Manual LED - set initial state
            config['initial_state'] = self._prompt(
                "Initial state (on/off)",
                "off"
            ).lower() == 'on'
        
        # Step 4: LED Color
        print("\n🎨 Step 4: LED Color")
        color_idx = self._prompt_choice("Select LED color", self.COLORS, default=1)
        config['color'] = self.COLORS[color_idx]
        
        # Step 5: Size
        config['size'] = self._prompt("LED size (diameter in pixels)", "24")
        
        # Step 6: Grid position
        print("\n📍 Step 5: Grid Position")
        config['row'] = int(self._prompt("Grid row", "1"))
        config['column'] = int(self._prompt("Grid column", "1"))
        
        # Print summary
        self.print_summary("LED Widget", config)
        
        # Generate XML
        return self._generate_xml(config)
    
    def _generate_xml(self, config: Dict) -> str:
        """
        Generate LED widget XML from configuration.
        
        Args:
            config: Widget configuration
            
        Returns:
            XML string
        """
        source = config.get('source')
        
        # Build position attributes
        position = self._generate_position(config['row'], config['column'])
        
        # Start widget
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!--',
            f'  LED Widget: {config["title"]}',
            f'  Generated by BIFF Agents - Marvin GUI Composer',
            '-->',
            f'<Widget File="{self.WIDGET_FILE}" {position}>',
        ]
        
        # Add title
        if config['title']:
            xml_lines.append(f'    <Title>{config["title"]}</Title>')
        
        # Add data source
        if source:
            xml_lines.append(f'    {self._generate_minion_src(source)}')
            
            # Add condition for turning LED on
            condition_type = config['condition_type']
            condition_value = config['condition_value']
            
            if condition_type == '==':
                xml_lines.append(f'    <OnCondition>{condition_value}</OnCondition>')
            elif condition_type == '>':
                xml_lines.append(f'    <OnCondition>&gt;{condition_value}</OnCondition>')
            elif condition_type == '<':
                xml_lines.append(f'    <OnCondition>&lt;{condition_value}</OnCondition>')
        else:
            # Static LED
            initial = "1" if config.get('initial_state', False) else "0"
            xml_lines.append(f'    <InitialValue>{initial}</InitialValue>')
        
        # Add color
        xml_lines.append(f'    <Color>{config["color"]}</Color>')
        
        # Add size
        xml_lines.append(f'    <Height>{config["size"]}</Height>')
        xml_lines.append(f'    <Width>{config["size"]}</Width>')
        
        # Close widget
        xml_lines.append('</Widget>')
        
        return '\n'.join(xml_lines)


# CLI entry point
def main():
    """Command-line interface for LED widget builder"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Create Marvin LED widget configuration'
    )
    parser.add_argument(
        '-c', '--config',
        type=Path,
        help='Path to MinionConfig.xml for data source discovery'
    )
    parser.add_argument(
        '-o', '--output',
        type=Path,
        help='Output file path for widget XML'
    )
    
    args = parser.parse_args()
    
    # Create builder
    builder = LEDWidgetBuilder(args.config)
    
    # Generate widget
    xml = builder.create_widget(args.output)
    
    if xml and not args.output:
        # Print to stdout if no output file
        print("\nGenerated XML:")
        print("=" * 70)
        print(xml)


if __name__ == '__main__':
    main()
