"""
Text Widget Builder

Creates text display widgets for showing dynamic or static text values.
Supports data binding to Minion sources, styling, and alignment.
"""

from pathlib import Path
from typing import Optional, Dict

from .widget_builder import WidgetBuilder
from ..utils.minion_discovery import DataSource


class TextWidgetBuilder(WidgetBuilder):
    """Builder for text display widgets"""
    
    WIDGET_FILE = "Text/Text.xml"
    
    ALIGNMENTS = [
        "Center",
        "North",
        "South", 
        "East",
        "West",
        "NorthWest",
        "NorthEast",
        "SouthWest",
        "SouthEast"
    ]
    
    FONT_SIZES = [
        "1.0em (Small)",
        "1.5em (Medium)",
        "2.0em (Large)",
        "3.0em (Extra Large)",
        "4.0em (Huge)",
        "Custom"
    ]
    
    def build_widget(self) -> str:
        """
        Interactive wizard to create text widget.
        
        Returns:
            Widget XML string
        """
        config = {}
        
        # Step 1: Title/Label
        config['title'] = self._prompt("Widget title/label", "Text Display")
        
        # Step 2: Data source selection
        print("\n📊 Step 2: Data Source")
        print("Select a data source to display dynamic values, or skip for static text.")
        
        source = self.select_data_source()
        config['source'] = source
        
        # Step 3: Initial/static value (if no source)
        if source is None:
            config['initial_value'] = self._prompt(
                "Static text value",
                "Sample Text"
            )
        else:
            # Optional: Add units or suffix
            use_units = self._prompt(
                "Show units/suffix? (y/n)",
                "y" if source.suggested_unit else "n"
            ).lower() == 'y'
            
            if use_units:
                default_unit = source.suggested_unit or ""
                config['units'] = self._prompt("Unit text", default_unit)
            else:
                config['units'] = ""
        
        # Step 4: Font size
        print("\n📏 Step 3: Font Size")
        font_idx = self._prompt_choice("Select font size", self.FONT_SIZES, default=2)
        
        if font_idx == len(self.FONT_SIZES) - 1:  # Custom
            config['font_size'] = self._prompt("Custom font size (e.g., 2.5em)", "2.0em")
        else:
            # Extract size from option (e.g., "1.5em (Medium)" -> "1.5em")
            config['font_size'] = self.FONT_SIZES[font_idx].split()[0]
        
        # Step 5: Alignment
        print("\n📍 Step 4: Alignment")
        align_idx = self._prompt_choice("Select alignment", self.ALIGNMENTS, default=1)
        config['alignment'] = self.ALIGNMENTS[align_idx]
        
        # Step 6: Grid position
        print("\n🎯 Step 5: Grid Position")
        config['row'] = int(self._prompt("Grid row", "1"))
        config['column'] = int(self._prompt("Grid column", "1"))
        
        # Optional: Spanning
        span_choice = self._prompt("Enable column/row spanning? (y/n)", "n")
        if span_choice.lower() == 'y':
            config['col_span'] = int(self._prompt("Column span", "1"))
            config['row_span'] = int(self._prompt("Row span", "1"))
        else:
            config['col_span'] = 1
            config['row_span'] = 1
        
        # Print summary
        self.print_summary("Text Widget", config)
        
        # Generate XML
        return self._generate_xml(config)
    
    def _generate_xml(self, config: Dict) -> str:
        """
        Generate text widget XML from configuration.
        
        Args:
            config: Widget configuration
            
        Returns:
            XML string
        """
        source = config.get('source')
        
        # Build position attributes
        position = self._generate_position(
            config['row'],
            config['column'],
            config.get('row_span', 1),
            config.get('col_span', 1)
        )
        
        # Build alignment attribute
        align_attr = f' Align="{config["alignment"][0]}"'  # First letter (C, N, S, etc.)
        
        # Start widget
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!--',
            f'  Text Widget: {config["title"]}',
            f'  Generated by BIFF Agents - Marvin GUI Composer',
            '-->',
            f'<Widget File="{self.WIDGET_FILE}" {position}{align_attr}>',
        ]
        
        # Add title if provided
        if config['title']:
            xml_lines.append(f'    <Title>{config["title"]}</Title>')
        
        # Add data source or static value
        if source:
            xml_lines.append(f'    {self._generate_minion_src(source)}')
            
            # Add units if specified
            if config.get('units'):
                xml_lines.append(f'    <Suffix> {config["units"]}</Suffix>')
        else:
            # Static text
            xml_lines.append(f'    <InitialValue>{config["initial_value"]}</InitialValue>')
        
        # Add style override for font size
        if config.get('font_size') and config['font_size'] != '1.5em':
            xml_lines.extend([
                '    <StyleOverride>',
                '        <Item>',
                f'            -fx-font-size: {config["font_size"]};',
                '        </Item>',
                '    </StyleOverride>',
            ])
        
        # Close widget
        xml_lines.append('</Widget>')
        
        return '\n'.join(xml_lines)


# CLI entry point
def main():
    """Command-line interface for text widget builder"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Create Marvin text widget configuration'
    )
    parser.add_argument(
        '-c', '--config',
        type=Path,
        help='Path to MinionConfig.xml for data source discovery'
    )
    parser.add_argument(
        '-o', '--output',
        type=Path,
        help='Output file path for widget XML'
    )
    
    args = parser.parse_args()
    
    # Create builder
    builder = TextWidgetBuilder(args.config)
    
    # Generate widget
    xml = builder.create_widget(args.output)
    
    if xml and not args.output:
        # Print to stdout if no output file
        print("\nGenerated XML:")
        print("=" * 70)
        print(xml)


if __name__ == '__main__':
    main()
