"""
Container Stats Collector
Auto-generated by BIFF Collector Builder

Plugin with Framework Interface for dynamic collector registration
Discovery Mode: dynamic
"""

import sys

def collect_containers(frameworkInterface):
    """
    Main entry point for Container Stats collection with framework interface
    
    Args:
        frameworkInterface: Minion framework interface providing:
            - Logger: Logger instance for logging
            - AddCollector(id): Register new collector dynamically
            - DoesCollectorExist(id): Check if collector already exists
            - SetCollectorValue(id, value): Update collector value
    
    Returns:
        str: "HelenKeller" to suppress standard output (framework handles data)
    """
    # Get logger from framework
    Logger = frameworkInterface.Logger
    
    try:
        Logger.info("Starting Container Stats collector")
        
        # Dynamic discovery example
        # Discover collectors at runtime (e.g., Docker containers, network devices)
        
        # TODO: Implement your discovery logic
        # Example: discovered_items = get_active_items()
        discovered_items = []  # Replace with actual discovery
        
        # Register and update collectors dynamically
        for item in discovered_items:
            collector_id = f"item.{item['name']}.{item['metric']}"
            
            # Register collector if it doesn't exist
            if not frameworkInterface.DoesCollectorExist(collector_id):
                frameworkInterface.AddCollector(collector_id)
                Logger.info(f"Registered new collector: {collector_id}")
            
            # Update collector value
            frameworkInterface.SetCollectorValue(collector_id, item['value'])
        
        Logger.info(f"Updated {len(discovered_items)} collectors")
        
    except Exception as Ex:
        Logger.error(f"Error in Container Stats collector: {Ex}")
    
    # Return "HelenKeller" to suppress standard output
    # Framework interface handles all data transmission
    return "HelenKeller"


if __name__ == '__main__':
    # Test mode - create mock framework interface
    class MockFramework:
        class MockLogger:
            def info(self, msg): print(f"INFO: {msg}")
            def error(self, msg): print(f"ERROR: {msg}", file=sys.stderr)
        
        def __init__(self):
            self.Logger = self.MockLogger()
            self.collectors = {}
        
        def AddCollector(self, id):
            self.collectors[id] = None
            print(f"Added collector: {id}")
        
        def DoesCollectorExist(self, id):
            return id in self.collectors
        
        def SetCollectorValue(self, id, value):
            self.collectors[id] = value
            print(f"Set {id} = {value}")
    
    # Run with mock framework
    mock = MockFramework()
    result = collect_containers(mock)
    print(f"\nReturn value: {result}")
    print(f"Registered collectors: {list(mock.collectors.keys())}")
