"""
ï»¿Network Queue Stats Collector
Auto-generated by BIFF Collector Builder

Plugin with Framework Interface for dynamic collector registration
Discovery Mode: static
"""

import sys

# Static collector IDs
COLLECTOR_IDS = ["queue.0.tx", "queue.0.rx", "queue.1.tx", "queue.1.rx"]

def collect_queue_stats(frameworkInterface):
    """
    Main entry point for ï»¿Network Queue Stats collection with framework interface
    
    Args:
        frameworkInterface: Minion framework interface providing:
            - Logger: Logger instance for logging
            - AddCollector(id): Register new collector dynamically
            - DoesCollectorExist(id): Check if collector already exists
            - SetCollectorValue(id, value): Update collector value
    
    Returns:
        str: "HelenKeller" to suppress standard output (framework handles data)
    """
    # Get logger from framework
    Logger = frameworkInterface.Logger
    
    try:
        Logger.info("Starting ï»¿Network Queue Stats collector")
        
        # Static collector IDs (defined at config time)
        
        for collector_id in COLLECTOR_IDS:
            # TODO: Implement collection logic for each ID
            value = "0"  # Replace with actual collection
            
            # Register collector if it doesn't exist
            if not frameworkInterface.DoesCollectorExist(collector_id):
                frameworkInterface.AddCollector(collector_id)
                Logger.info(f"Registered collector: {collector_id}")
            
            # Update collector value
            frameworkInterface.SetCollectorValue(collector_id, value)
        
        Logger.info(f"Updated {len(COLLECTOR_IDS)} collectors")
        
    except Exception as Ex:
        Logger.error(f"Error in ï»¿Network Queue Stats collector: {Ex}")
    
    # Return "HelenKeller" to suppress standard output
    # Framework interface handles all data transmission
    return "HelenKeller"


if __name__ == '__main__':
    # Test mode - create mock framework interface
    class MockFramework:
        class MockLogger:
            def info(self, msg): print(f"INFO: {msg}")
            def error(self, msg): print(f"ERROR: {msg}", file=sys.stderr)
        
        def __init__(self):
            self.Logger = self.MockLogger()
            self.collectors = {}
        
        def AddCollector(self, id):
            self.collectors[id] = None
            print(f"Added collector: {id}")
        
        def DoesCollectorExist(self, id):
            return id in self.collectors
        
        def SetCollectorValue(self, id, value):
            self.collectors[id] = value
            print(f"Set {id} = {value}")
    
    # Run with mock framework
    mock = MockFramework()
    result = collect_queue_stats(mock)
    print(f"\nReturn value: {result}")
    print(f"Registered collectors: {list(mock.collectors.keys())}")
